<a href="https://colab.research.google.com/github/rajgsdei/py-learning/blob/main/basic_torch_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
import torch

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

arr = "test"
print(type(arr))

arr = [1,2,3,4,5]
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'str'>
[1, 2, 3, 4, 5]
<class 'list'>


In [46]:
x = np.random.rand(2, 3)
print(x)
print(type(arr))

[[0.70711666 0.32753884 0.69147799]
 [0.74049945 0.35774747 0.81364939]]
<class 'list'>


In [39]:
_tensor = torch.randn(2,3, 4)
print(_tensor)

tensor([[[ 0.6534,  0.5424, -1.0555, -0.1067],
         [-0.7979, -0.3320, -0.4464,  0.1220],
         [-0.0844, -0.6400,  0.8054,  0.6059]],

        [[-0.6974, -1.2655,  0.2730,  0.4189],
         [-0.5243, -0.9600,  0.2682, -0.6549],
         [-0.8560, -0.7033, -0.2813, -0.3370]]])


In [45]:
_tensor = torch.zeros(2,3, 4)
print(_tensor)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [52]:
tensor_from_array = torch.tensor(x)
print(tensor_from_array)

tensor([[0.7071, 0.3275, 0.6915],
        [0.7405, 0.3577, 0.8136]], dtype=torch.float64)


In [76]:
#chapter 2
my_torch = torch.arange(5);
print(my_torch)
my_torch1 = my_torch.reshape(-1,5)
print(my_torch1)

my_torch2 = my_torch.add(my_torch1)
print(my_torch2)

tensor([0, 1, 2, 3, 4])
tensor([[0, 1, 2, 3, 4]])
tensor([[0, 2, 4, 6, 8]])


In [84]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([3,4,2,0,7])
z = x.add_(y)
x
z

tensor([ 4,  6,  5,  4, 12])